var cuesDrawnShape=null;function icuesDrawnShape(){var N=navigator.userAgent.indexOf("MSIE")!=-1;var az=navigator.userAgent.indexOf("Firefox/")!=-1;var t=navigator.userAgent.indexOf("Safari")!=-1;if(N&&!t){this.makeTab=I;this.adjustTab=M;this.makeTabActive=h;this.makeTabInactive=y;this.tabMouseover=D;this.tabMouseout=A;this.renderTabset=aF;this.makePrimaryTabset=K;this.makePrimaryTab=ak;this.makePrimaryTabActive=X;this.makePrimaryTabInactive=ap;this.primarytabMouseover=aG;
this.primarytabMouseout=ag;this.makeSecondaryTab=an;this.makeSecondaryTabActive=al;this.makeSecondaryTabInactive=Y;this.secondarytabMouseover=ah;this.secondarytabMouseout=E;this.makeDrawer=x;this.adjustDrawer=Q;this.makeDrawerActive=aA;this.makeDrawerInactive=aw;this.drawerMouseover=S;this.drawerMouseout=f;this.makeDashboard=ax;this.makePanel=aD;this.makeToolbar=aM;this.makeContainer=R;this.makeProgressBar=p;this.updateProgressBar=G;try{document.namespaces.add("cues_vml","urn:schemas-microsoft-com:vml")
}catch(aC){}}else{this.makeTab=i;this.adjustTab=H;this.makeTabActive=aK;this.makeTabInactive=L;this.tabMouseover=ad;this.tabMouseout=aJ;this.renderTabset=ar;this.makePrimaryTabset=T;this.makePrimaryTab=b;this.makePrimaryTabActive=J;this.makePrimaryTabInactive=g;this.primarytabMouseover=P;this.primarytabMouseout=m;this.makeSecondaryTab=l;this.makeSecondaryTabActive=U;this.makeSecondaryTabInactive=j;this.secondarytabMouseover=ab;this.secondarytabMouseout=a;
this.makeDrawer=o;this.adjustDrawer=d;this.makeDrawerActive=W;this.makeDrawerInactive=C;this.drawerMouseover=aj;this.drawerMouseout=aL;this.makeDashboard=ac;this.makePanel=z;this.makeToolbar=B;this.makeContainer=k;this.makeProgressBar=r;this.updateProgressBar=ao}this.toggleTab=at;this.togglePrimaryTab=O;this.toggleSecondaryTab=s;var aH=null;var q=null;var n=null;var av=null;var aa=null;var aN=null;var aE=null;var aI=null;var u=null;var c=null;var aq=null;
var F=null;var V="http://www.w3.org/2000/svg";var au=null;var am="20%";var ay="21%";var af="50%";var v="51%";var Z="50%";var ae="51%";var ai="25%";var aB="25.1%";w();function at(aQ,aS){var aP=-1;var aO=document.getElementById(aQ);if(aO==null){return}var aR=Math.ceil(aO.rows[0].cells.length/2);for(var e=0;e<aR;e++){if(e==aS){continue}var aO=document.getElementById(aQ+"_"+e+"_tab");if(aO==null){break}if(aO.active=="true"){aP=e;cuesDrawnShape.makeTabInactive(aQ,e);
break}}cuesDrawnShape.makeTabActive(aQ,aS);return aP}function O(aQ,aU,aT,aS){var aP=-1;var aO=document.getElementById(aQ).getElementsByTagName("table")[0];if(aO==null){return}var aR=Math.ceil(aO.rows[0].cells.length);for(var e=0;e<aR;e++){if(e==aU){continue}var aO=document.getElementById(aQ+"_"+e+"_tab");if(aO==null){break}if(aO.active=="true"){aP=e;cuesDrawnShape.makePrimaryTabInactive(aQ,e);break}}cuesDrawnShape.makePrimaryTabActive(aQ,aU);if(aT){cuesInvokeTab(aS,document.getElementById(aQ+"_"+aU+"_tab"),true)
}return aP}function s(aQ,aU,aT,aS){var aP=-1;var aO=document.getElementById(aQ).getElementsByTagName("table")[0];if(aO==null){return}var aR=Math.ceil(aO.rows[0].cells.length);for(var e=0;e<aR;e++){if(e==aU){continue}var aO=document.getElementById(aQ+"_"+e+"_tab");if(aO==null){break}if(aO.active=="true"){aP=e;cuesDrawnShape.makeSecondaryTabInactive(aQ,e);break}}cuesDrawnShape.makeSecondaryTabActive(aQ,aU);if(aT){cuesInvokeTab(aS,document.getElementById(aQ+"_"+aU+"_tab"))
}return aP}function h(aO,aU){var e=document.getElementById(aO+"_"+aU+"_fill");e.color=au.cuesTabActiveStartGradient;e.color2=au.cuesTabActiveStopGradient;e.opacity=0.4;e.angle=-180;e.colors.value="";var aT=document.getElementById("cuesid_"+aO+"_"+aU);var aQ=aT.offsetWidth;aT.style.color="";var e=document.getElementById(aO+"_"+aU+"_tab");var aR=e.offsetWidth;e.className="cuesTab cuesTabCaptionActive";e.active="true";var aS=document.getElementById(aO+"_"+aU+"_base");
if(aS!=null){aS.style.display="none"}var aP=document.getElementById(aO+"_"+aU+"_stroke");if(aP!=null){aP.color=au.cuesTabActiveStroke}var aW=e.offsetWidth;var aV=aT.offsetWidth;M(aO,aU,aW-aR)}function aK(aO,e){var aR=document.getElementById(aO+"_"+e+"_tab");var aQ=aR.offsetWidth;var aS=document.getElementById("cuesid_"+aO+"_"+e);var aP=aS.offsetWidth;aR.className="cuesTab cuesTabCaptionActive";aR.active="true";aS.style.color="";var aT=aR.getElementsByTagName("rect");
aT[1].style.cssText=aT[1].style.cssText.replace("#inactivetab_grad","#activetab_grad");aT[1].style.cssText=aT[1].style.cssText.replace("#hovertab_grad","#activetab_grad");aT[1].setAttributeNS(null,"stroke",au.cuesTabActiveStroke);var aW=aR.getElementsByTagName("line");aW[0].style.display="none";var aV=aR.offsetWidth;var aU=aS.offsetWidth;H(aO,e,aU-aP)}function y(aO,aU){var e=document.getElementById(aO+"_"+aU+"_fill");e.color=au.cuesTabInactiveStartGradient;
e.color2=au.cuesTabInactiveStopGradient;e.opacity="100%";e.angle=180;e.colors.value=e.inactivecolors;var e=document.getElementById(aO+"_"+aU+"_tab");var aR=e.offsetWidth;var aT=document.getElementById("cuesid_"+aO+"_"+aU);var aQ=aT.offsetWidth;e.className="cuesTab cuesTabCaptionInactive";e.active="false";var aS=document.getElementById(aO+"_"+aU+"_base");if(aS!=null){aS.style.display=""}var aP=document.getElementById(aO+"_"+aU+"_stroke");if(aP!=null){aP.color=au.cuesTabInactiveStroke
}var aW=e.offsetWidth;var aV=aT.offsetWidth;M(aO,aU,aV-aQ)}function L(aO,e){var aR=document.getElementById(aO+"_"+e+"_tab");var aQ=aR.offsetWidth;var aS=document.getElementById("cuesid_"+aO+"_"+e);var aP=aS.offsetWidth;aR.className="cuesTab cuesTabCaptionInactive";aR.active="false";var aT=aR.getElementsByTagName("rect");aT[1].style.cssText=aT[1].style.cssText.replace("#activetab_grad","#inactivetab_grad");aT[1].setAttributeNS(null,"stroke",au.cuesTabInactiveStroke);
var aW=aR.getElementsByTagName("line");aW[0].style.display="";var aV=aR.offsetWidth;var aU=aS.offsetWidth;H(aO,e,aU-aP)}function M(aQ,aU,e,aP){var aR=document.getElementById(aQ+"_"+aU+"_tab");if(aR==null){return}var aO=aR.getElementsByTagName("roundrect");if(aO.length==0){return}var aS=aR.offsetWidth;if(e!=null){aR.style.width=aS+e;aO[0].style.width=aS+e}if(aP!=null){aR.style.width=aP;aO[0].style.width=aP}var aT=document.getElementById(aQ+"_"+aU+"_base");
if(aT.offsetWidth>0){aT.to.x=(aT.to.x/aS)*(aS+e)}}function H(aQ,aS,e,aP){var aR=document.getElementById(aQ+"_"+aS+"_tab");if(aR==null){return}var aO=aR.getElementsByTagName("rect");if(aO.length==0){return}if(e!=null){aR.style.width=aR.offsetWidth+e}if(aP!=null){aR.style.width=aP}}function aF(e){for(var aR=0;aR<20;aR++){var aO=document.getElementById(e+"_"+aR+"_tab");if(aO==null){return}aO.style.width="auto";var aT=aO.getElementsByTagName("roundrect");
if(aT.length==0){return}aT[0].style.width=aO.offsetWidth;var aS=aO.offsetHeight;var aQ=aO.offsetWidth;aT[0].style.height=Math.ceil(aS*1.2)+"px";aT[0].style.clip="rect(0,auto,"+(aS+1)+",auto)";var aP=document.getElementById(e+"_"+aR+"_base");if(aP==null){return}aP.setAttribute("from","0,"+(aS-1));aP.setAttribute("to",aQ+","+(aS-1))}}function ar(aO){for(var e=0;e<20;e++){var aP=document.getElementById(aO+"_"+e+"_tab");if(aP==null){return}aP.style.width="auto";
var aQ=aP.getElementsByTagName("svg");if(aQ.length==0){return}aQ[0].setAttributeNS(null,"height",(aP.offsetHeight-2)+"px")}}function I(aP,aU,aW,e){var aQ=document.getElementById(aP+"_"+aU+"_tab");if(aQ==null){return}var aS=aQ.offsetHeight;if(aS==0&&e==null){setTimeout("cuesDrawnShape.makeTab('"+aP+"',"+aU+","+aW+",true)",10);return}var aO=aQ.offsetWidth;if(aS==0){aS=20}if(aO==0){aO=100}aQ.style.height=aS;aQ.style.width=aO;var aY=aQ.offsetWidth;if(aY==0){aY="100%"
}if(aY>aQ.scrollWidth&&aY>1000){aY=aQ.scrollWidth}aQ.style.width=aY;var aR=document.createElement("div");aR.style.position="absolute";aR.style.top="0px";aR.style.left="0px";aR.style.zIndex="-1";var aX=aW?"Active":"Inactive";aQ.active=aW?"true":"false";var aV="";aV+='<cues_vml:roundrect style="height:'+Math.ceil(aS*1.2)+"px;width:"+aY+"px;position:absolute;padding:0;top:1px;left:0px;margin:0;padding:0px;clip:rect(0,auto,"+aS+',auto);" arcsize="0.1">';
aV+='<cues_vml:stroke id="'+aP+"_"+aU+'_stroke" dashstyle="solid" color="'+au["cuesTab"+aX+"Stroke"]+'"/>';aV+='<cues_vml:fill id="'+aP+"_"+aU+'_fill" type="gradient"';if(!aW){aV+=' angle="180" colors="33% '+au.cuesTabInactiveStopGradient1+", 34% "+au.cuesTabInactiveStartGradient2+", 49% "+au.cuesTabInactiveStopGradient2+", 50% "+au.cuesTabInactiveStartGradient3+'"'}else{aV+=' angle="-180" opacity="40%" '}aV+=' inactivecolors="16% '+au.cuesTabInactiveStopGradient1+", 17% "+au.cuesTabInactiveStartGradient2+", 42% "+au.cuesTabInactiveStopGradient2+", 43% "+au.cuesTabInactiveStartGradient3+'"';
aV+=' hovercolors="42% '+au.cuesTabHoverStopGradient1+", 43% "+au.cuesTabHoverStartGradient2+'"';aV+=' color="'+au["cuesTab"+aX+"StartGradient"]+'"';aV+=' color2="'+au["cuesTab"+aX+"StopGradient"]+'"/>';aV+="</cues_vml:roundrect>";aV+='<cues_vml:line id="'+aP+"_"+aU+'_base" from="0,'+(aS-1)+'" to="'+aY+","+(aS-1)+'" strokecolor="'+au.cuesTabStroke+'" strokeweight="1px"/>';aR.innerHTML=aV;aQ.appendChild(aR);if(aW){var aT=document.getElementById(aP+"_"+aU+"_base");
if(aT!=null){aT.style.display="none"}}}function i(aP,aO,aU){var aQ=document.getElementById(aP+"_"+aO+"_tab");if(aQ==null){return}var aS=aQ.offsetHeight;var aX=aQ.offsetWidth;aQ.style.width=aX;var aV=aU?"Active":"Inactive";aQ.active=aU?"true":"false";var aY=document.createElementNS(V,"svg");aY.setAttributeNS(null,"style","position:absolute;top:2px;left:0px;z-index:-1;");aY.setAttributeNS(null,"height",(aQ.offsetHeight-2)+"px");aQ.appendChild(aY);if(q==null){var aZ="";
aZ+='<svg xmlns="http://www.w3.org/2000/svg">';aZ+="<defs>";aZ+='<linearGradient id="activetab_grad" x1="0" y1="0" x2="0" y2="100%">';aZ+='<stop offset="0%" style="stop-color:'+au.cuesTabActiveStartGradient+';stop-opacity:1;"/>';aZ+='<stop offset="50%" style="stop-color:'+au.cuesTabActiveStartGradient+';stop-opacity:.40;"/>';aZ+="</linearGradient>";aZ+='<linearGradient id="hovertab_grad" x1="0" y1="0" x2="0" y2="100%">';aZ+='<stop offset="0%" style="stop-color:'+au.cuesTabHoverStartGradient+';stop-opacity:1;"/>';
aZ+='<stop offset="25%" style="stop-color:'+au.cuesTabHoverStopGradient1+';stop-opacity:1;"/>';aZ+='<stop offset="26%" style="stop-color:'+au.cuesTabHoverStartGradient2+';stop-opacity:1;"/>';aZ+='<stop offset="50%" style="stop-color:'+au.cuesTabHoverStopGradient+';stop-opacity:1;"/>';aZ+="</linearGradient>";aZ+='<clipPath id="activetab_clip">';aZ+='<rect x="0" y="0" width="100%" height="100%"/>';aZ+="</clipPath>";aZ+="</defs>";aZ+='<rect rx="5" ry="5" x="0" y="0" width="100%" height="200%" stroke="'+au.cuesTabActiveStroke+'" style="fill:url(#activetab_grad);stroke-width:1.5px;"/>';
aZ+='<line x1="0" y1="'+(aS-2)+'" x2="500" y2="'+(aS+1)+'" style="display:none;stroke:'+au.cuesTabStroke+';stroke-width:1px;stroke-opacity:1.5;"/>';aZ+="</svg>";var aR=new DOMParser();q=aR.parseFromString(aZ,"text/xml")}if(n==null){var aZ="";aZ+='<svg xmlns="http://www.w3.org/2000/svg">';aZ+="<defs>";aZ+='<linearGradient id="inactivetab_grad" x1="0" y1="0" x2="0" y2="100%">';aZ+='<stop offset="0%" style="stop-color:'+au.cuesTabInactiveStartGradient+';stop-opacity:1;"/>';
aZ+='<stop offset="10%" style="stop-color:'+au.cuesTabInactiveStopGradient1+';stop-opacity:1;"/>';aZ+='<stop offset="25%" style="stop-color:'+au.cuesTabInactiveStartGradient2+';stop-opacity:1;"/>';aZ+='<stop offset="26%" style="stop-color:'+au.cuesTabInactiveStopGradient2+';stop-opacity:1;"/>';aZ+='<stop offset="50%" style="stop-color:'+au.cuesTabInactiveStopGradient+';stop-opacity:1;"/>';aZ+="</linearGradient>";aZ+='<clipPath id="inactivetab_clip">';
aZ+='<rect x="0" y="0" width="100%" height="100%"/>';aZ+="</clipPath>";aZ+="</defs>";aZ+='<rect rx="5" ry="5" x="0" y="0" width="100%" height="200%" stroke="'+au.cuesTabInactiveStroke+'" style="fill:url(#inactivetab_grad);stroke-width:1.5px;"/>';aZ+='<line x1="0" y1="'+(aS-2)+'" x2="500" y2="'+(aS-2)+'" style="z-index:1;fill:'+au.cuesTabStroke+";stroke:"+au.cuesTabStroke+';stroke-width:1px;stroke-opacity:1.5"/>';aZ+="</svg>";var aR=new DOMParser();
n=aR.parseFromString(aZ,"text/xml")}var aW;if(aU){aW=q.documentElement}else{aW=n.documentElement}var e=aW.childNodes.length;for(var aT=0;aT<e;++aT){aY.appendChild(document.importNode(aW.childNodes[aT],true))}}function D(aO,e){var aP=document.getElementById(aO+"_"+e+"_tab");if(aP==null){return}if(aP.active=="true"){return}var aQ=document.getElementById("cuesid_"+aO+"_"+e);aQ.style.color=au.cuesTabCaptionHover;var aP=document.getElementById(aO+"_"+e+"_fill");
if(aP!=null){aP.color=au.cuesTabHoverStartGradient;aP.color2=au.cuesTabHoverStopGradient;aP.colors.value=aP.hovercolors;aP.colors.value="42% "+au.cuesTabHoverStopGradient1+", 43% "+au.cuesTabHoverStartGradient2}var aP=document.getElementById(aO+"_"+e+"_stroke");if(aP!=null){aP.color=au.cuesTabHoverStroke}}function A(aO,e){var aP=document.getElementById(aO+"_"+e+"_tab");if(aP==null){return}if(aP.active=="true"){return}var aQ=document.getElementById("cuesid_"+aO+"_"+e);
aQ.style.color=au.cuesTabCaptionInactive;var aP=document.getElementById(aO+"_"+e+"_fill");if(aP!=null){aP.color=au.cuesTabInactiveStartGradient;aP.color2=au.cuesTabInactiveStopGradient;aP.colors.value=aP.inactivecolors}var aP=document.getElementById(aO+"_"+e+"_stroke");if(aP!=null){aP.color=au.cuesTabInactiveStroke}}function ad(aR,aP){var e=document.getElementById(aR+"_"+aP+"_tab");if(e==null){return}if(e.active=="true"){return}var aO=document.getElementById("cuesid_"+aR+"_"+aP);
aO.style.color=au.cuesTabCaptionHover;var aQ=e.getElementsByTagName("rect")[1];aQ.style.cssText=aQ.style.cssText.replace("url(#inactivetab_grad)","url(#hovertab_grad)");aQ.setAttributeNS(null,"stroke",au.cuesTabHoverStroke)}function aJ(aR,aP){var e=document.getElementById(aR+"_"+aP+"_tab");if(e==null){return}if(e.active=="true"){return}var aO=document.getElementById("cuesid_"+aR+"_"+aP);aO.style.color=au.cuesTabCaptionInactive;var aQ=e.getElementsByTagName("rect")[1];
aQ.style.cssText=aQ.style.cssText.replace("url(#hovertab_grad)","url(#inactivetab_grad)");aQ.setAttributeNS(null,"stroke",au.cuesTabInactiveStroke)}function K(aP,aV){var aQ=document.getElementById(aP);if(aQ==null){return}var aU=aQ.offsetHeight;if(aU==0&&aV==null){setTimeout("cuesDrawnShape.makePrimaryTabset('"+aP+"',true)",250);return}var aS=aQ.getElementsByTagName("table")[0];var aW=aS.rows.length;if(cuesUsage+""=="portal"&&aW>1){aU+=3}var e=aS.rows[0].offsetHeight;
var aO=Math.floor(e/2);var aR=aU-e-2;aQ.style.height=aU;var aT=document.createElement("div");aT.style.position="absolute";aT.style.top="0px";aT.style.left="0px";aT.style.width="100%";aT.style.zIndex="-2";var aX="";aX+='<cues_vml:roundrect style="position:absolute;height:'+e+'px;width:100%;" arcsize="0.05" filled="f" strokecolor="'+au.cuesPrimaryTabsetStroke+'">';aX+='<cues_vml:stroke opacity=".5"/>';aX+="</cues_vml:roundrect>";aX+='<div style="height:'+(aO+1)+'px;padding-right:2px;padding-left:2px;padding-top:2px;">';
aX+='<cues_vml:roundrect style="position:absolute;height:'+aO+'px;width:100%;" arcsize="0.05" fillcolor="'+au.cuesPrimaryTabsetStartGradient+'" stroked="f">';aX+='<cues_vml:fill color2="'+au.cuesPrimaryTabsetStopGradient+'" opacity="0.30" angle="-180"/>';aX+="</cues_vml:roundrect>";aX+="</div>";if(cuesUsage+""=="portal"&&aW>1){aX+='<cues_vml:roundrect style="position:absolute;top:'+(e+1)+"px;height:"+aR+'px;width:100%;" arcsize="0.05" fillcolor="#ffffff;" stroked="f">';
aX+='<cues_vml:fill color2="#ffffff" opacity="0.67" angle="-180"/>';aX+="</cues_vml:roundrect>"}aT.innerHTML=aX;aQ.appendChild(aT)}function T(aP,aW){var aQ=document.getElementById(aP);if(aQ==null){return}var a0=document.createElementNS(V,"svg");a0.setAttributeNS(null,"style","position:absolute;top:0px;left:0px;z-index:-1;");a0.setAttributeNS(null,"height","31px");a0.setAttributeNS(null,"width","100%");aQ.appendChild(a0);var aS=aQ.getElementsByTagName("table")[0];
var aY=aS.rows.length;var aV=parseInt(aQ.offsetHeight);var aO=aS.rows[0].offsetHeight;var e=Math.floor(aO/2);var aR=aQ.offsetHeight-aO;a0.setAttributeNS(null,"height",aV+"px");if(av==null){var a1="";a1+='<svg xmlns="http://www.w3.org/2000/svg">';a1+="<defs>";a1+='<linearGradient id="primarytabset_grad" x1="0" y1="0" x2="0" y2="100%">';a1+='<stop offset="0%" style="stop-color:'+au.cuesPrimaryTabsetStartGradient+';stop-opacity:.3;"/>';a1+='<stop offset="100%" style="stop-color:'+au.cuesPrimaryTabsetStopGradient+';stop-opacity:.07;"/>';
a1+="</linearGradient>";a1+='<clipPath id="primarytabset_left_clip">';a1+='<rect x="0" y="0" width="50%" height="'+aO+'"/>';a1+="</clipPath>";a1+='<clipPath id="primarytabset_right_clip">';a1+='<rect x="50%" y="0" width="100%" height="'+aO+'"/>';a1+="</clipPath>";if(cuesUsage+""=="portal"&&aY>1){a1+='<clipPath id="primarytabsetmenu_left_clip">';a1+='<rect x="0" y="0" width="50%" height="100%"/>';a1+="</clipPath>";a1+='<clipPath id="primarytabsetmenu_right_clip">';
a1+='<rect x="50%" y="0" width="100%" height="100%"/>';a1+="</clipPath>"}a1+="</defs>";a1+='<rect rx="4" ry="4" x="0" y="0" width="100%" height="'+aO+'" style="fill:none;stroke:'+au.cuesPrimaryTabsetStroke+';stroke-width:1.5px;stroke-opacity:.5;"/>';a1+='<rect rx="2" ry="2" x="2" y="2" width="100%" height="'+e+'" style="fill:url(#primarytabset_grad);" clip-path="url(#primarytabset_left_clip)"/>';a1+='<rect rx="2" ry="2" x="-2" y="2" width="100%" height="'+e+'" style="fill:url(#primarytabset_grad);" clip-path="url(#primarytabset_right_clip)"/>';
if(cuesUsage+""=="portal"&&aY>1){a1+='<rect rx="2" ry="2" x="0"  y="'+aO+'" width="100%" height="'+aR+'px" style="opacity:.67;fill:#ffffff;" clip-path="url(#primarytabsetmenu_left_clip)"/>';a1+='<rect rx="2" ry="2" x="-2" y="'+aO+'" width="100%" height="'+aR+'px" style="opacity:.67;fill:#ffffff;" clip-path="url(#primarytabsetmenu_right_clip)"/>'}a1+="</svg>";var aT=new DOMParser();av=aT.parseFromString(a1,"text/xml")}var aZ=av.documentElement;var aX=aZ.childNodes.length;
for(var aU=0;aU<aX;++aU){a0.appendChild(document.importNode(aZ.childNodes[aU],true))}}function X(aO,aQ){var e=document.getElementById(aO+"_"+aQ+"_fill");e.color=au.cuesPrimaryTabActiveStartGradient;e.color2=au.cuesPrimaryTabActiveStopGradient;e.opacity=1;e.opacity2=1;e.angle=180;var aP=document.getElementById("cuesid_"+aO+"_"+aQ);aP.className="cuesPrimaryTabLink cuesShadowIE";aP.style.color="";var e=document.getElementById(aO+"_"+aQ+"_tab");e.className="cuesPrimaryTab cuesPrimaryTabCaptionActive";
e.active="true";var e=document.getElementById(aO+"_"+aQ+"_outline");e.color=au.cuesPrimaryTabActiveStroke;var e=document.getElementById(aO+"_"+aQ+"_shape");if(e!=null){e.style.display=""}}function J(aR,aO){var aQ=document.getElementById(aR+"_"+aO+"_tab");aQ.className="cuesPrimaryTab cuesPrimaryTabCaptionActive";aQ.active="true";var e=document.getElementById("cuesid_"+aR+"_"+aO);e.className="cuesPrimaryTabLink cuesShadowFF";e.style.color="";var aP=aQ.getElementsByTagName("rect");
aP[0].style.cssText=aP[0].style.cssText.replace("#hoverprimarytab_grad","#activeprimarytab_grad");aP[0].style.display="";aP[0].setAttributeNS(null,"stroke",au.cuesPrimaryTabActiveStroke)}function ap(e,aO){var aP=document.getElementById(e+"_"+aO+"_tab");aP.className="cuesPrimaryTab cuesPrimaryTabCaptionInactive";aP.opacity=0.3;aP.opacity2=0.07;aP.active="false";var aP=document.getElementById(e+"_"+aO+"_shape");aP.style.display="none"}function g(aO,aP){var e=document.getElementById(aO+"_"+aP+"_tab");
e.className="cuesPrimaryTab cuesPrimaryTabCaptionInactive";e.active="false";var aQ=e.getElementsByTagName("rect");aQ[0].style.display="none";aQ[0].setAttributeNS(null,"stroke",au.cuesPrimaryTabHoverStroke)}function ak(aP,aU,aW,e){var aQ=document.getElementById(aP+"_"+aU+"_tab");if(aQ==null){return}var aS=aQ.offsetHeight;if(aS==0&&e==null){setTimeout("cuesDrawnShape.makePrimaryTab('"+aP+"',"+aU+","+aW+",true)",10);return}var aO=aQ.offsetWidth;if(aS==0){aS=20
}if(aO==0){aO=100}aQ.style.height=aS+1;aQ.style.width=aO;var aX=aQ.offsetWidth;if(aX==0){aX="100%"}if(aX>aQ.scrollWidth&&aX>1000){aX=aQ.scrollWidth}aQ.style.width=aX;aQ.active=aW?"true":"false";var aR=document.createElement("div");aR.style.position="absolute";aR.style.top="0px";aR.style.left="0px";aR.style.zIndex="-1";var aV="";aV+='<cues_vml:roundrect id="'+aP+"_"+aU+'_shape" style="'+(aW?"":"display:none;")+"height:"+aS+"px;width:"+aX+'px;position:absolute;padding:0;top:0px;left:0px;margin:0;padding:0px;" arcsize="0.1">';
aV+='<cues_vml:stroke id="'+aP+"_"+aU+'_outline" dashstyle="solid" color="'+au.cuesPrimaryTabActiveStroke+'"/>';aV+='<cues_vml:fill id="'+aP+"_"+aU+'_fill" type="gradient"';aV+=' angle="180" ';aV+=' color="'+au.cuesPrimaryTabActiveStartGradient+'"';aV+=' color2="'+au.cuesPrimaryTabActiveStopGradient+'"/>';aV+="</cues_vml:roundrect>";aR.innerHTML=aV;aQ.appendChild(aR);var aT=document.getElementById("cuesid_"+aP+"_"+aU);aT.className="cuesPrimaryTabLink cuesShadowIE"
}function b(aP,aU,aW){var aQ=document.getElementById(aP+"_"+aU+"_tab");if(aQ==null){return}var e=aQ.offsetHeight;var aY=aQ.offsetWidth;aQ.style.width=aY;aQ.active=aW?"true":"false";var aZ=document.createElementNS(V,"svg");aZ.setAttributeNS(null,"style","position:absolute;top:0px;left:0px;z-index:-1;");aZ.setAttributeNS(null,"height",e+"px");aQ.appendChild(aZ);if(aa==null){var a0="";a0+='<svg xmlns="http://www.w3.org/2000/svg">';a0+="<defs>";a0+='<linearGradient id="activeprimarytab_grad" x1="0" y1="0" x2="0" y2="100%">';
a0+='<stop offset="0%" style="stop-color:'+au.cuesPrimaryTabActiveStartGradient+';stop-opacity:1;"/>';a0+='<stop offset="100%" style="stop-color:'+au.cuesPrimaryTabActiveStopGradient+';stop-opacity:1;"/>';a0+="</linearGradient>";a0+="</defs>";a0+='<rect rx="4" ry="4" x="0" y="0" width="100%" height="100%" stroke="'+au.cuesPrimaryTabActiveStroke+'" style="fill:url(#activeprimarytab_grad);stroke-width:1px;stroke-opacity:1;"/>';a0+="</svg>";var aO=new DOMParser();
aa=aO.parseFromString(a0,"text/xml")}if(aN==null){var a0="";a0+='<svg xmlns="http://www.w3.org/2000/svg">';a0+="<defs>";a0+='<linearGradient id="hoverprimarytab_grad" x1="0" y1="0" x2="0" y2="100%">';a0+='<stop offset="0%" style="stop-color:'+au.cuesPrimaryTabHoverStartGradient+';stop-opacity:1;"/>';a0+='<stop offset="100%" style="stop-color:'+au.cuesPrimaryTabHoverStopGradient+';stop-opacity:1;"/>';a0+="</linearGradient>";a0+="</defs>";a0+='<rect rx="4" ry="4" x="0" y="0" width="100%" height="100%" stroke="'+au.cuesPrimaryTabHoverStroke+'" style="display:none;fill:url(#hoverprimarytab_grad);stroke-width:1px;stroke-opacity:1;"/>';
a0+="</svg>";var aO=new DOMParser();aN=aO.parseFromString(a0,"text/xml")}var aX;if(aW){aX=aa.documentElement}else{aX=aN.documentElement}var aR=aX.childNodes.length;for(var aS=0;aS<aR;++aS){aZ.appendChild(document.importNode(aX.childNodes[aS],true))}var aT=document.getElementById("cuesid_"+aP+"_"+aU);var aV=aT.getElementsByTagName("span")[0].textContent;aT.setAttribute("shadowText",aV);aT.className="cuesPrimaryTabLink cuesShadowFF"}function aG(aO,e){var aP=document.getElementById(aO+"_"+e+"_tab");
if(aP==null){return}if(aP.active=="true"){return}var aQ=document.getElementById("cuesid_"+aO+"_"+e);aQ.className="cuesPrimaryTabLink";aQ.style.color=au.cuesPrimaryTabCaptionHover;var aP=document.getElementById(aO+"_"+e+"_fill");if(aP==null){return}aP.color=au.cuesPrimaryTabHoverStartGradient;aP.color2=au.cuesPrimaryTabHoverStopGradient;var aP=document.getElementById(aO+"_"+e+"_outline");aP.color=au.cuesPrimaryTabHoverStroke;var aP=document.getElementById(aO+"_"+e+"_shape");
if(aP==null){return}aP.style.display=""}function ag(aO,e){var aP=document.getElementById(aO+"_"+e+"_tab");if(aP==null){return}if(aP.active=="true"){return}var aQ=document.getElementById("cuesid_"+aO+"_"+e);aQ.className="cuesPrimaryTabLink cuesShadowIE";aQ.style.color=au.cuesPrimaryTabCaptionInactive;var aP=document.getElementById(aO+"_"+e+"_shape");if(aP==null){return}aP.style.display="none"}function P(aR,aP){var e=document.getElementById(aR+"_"+aP+"_tab");
if(e==null){return}if(e.active=="true"){return}var aO=document.getElementById("cuesid_"+aR+"_"+aP);aO.className="cuesPrimaryTabLink";aO.style.color=au.cuesPrimaryTabCaptionHover;var aQ=e.getElementsByTagName("rect")[0];aQ.style.cssText=aQ.style.cssText.replace("url(#activeprimarytab_grad)","url(#hoverprimarytab_grad)");aQ.style.display=""}function m(aR,aP){var e=document.getElementById(aR+"_"+aP+"_tab");if(e==null){return}if(e.active=="true"){return
}var aO=document.getElementById("cuesid_"+aR+"_"+aP);aO.className="cuesPrimaryTabLink cuesShadowFF";aO.style.color=au.cuesPrimaryTabCaptionInactive;var aQ=e.getElementsByTagName("rect")[0];aQ.style.display="none"}function al(aO,aQ){var e=document.getElementById(aO+"_"+aQ+"_fill");e.colors.value=e.activecolors;e.color=au.cuesSecondaryTabActiveStartGradient;e.color2=au.cuesSecondaryTabActiveStopGradient;var aP=document.getElementById("cuesid_"+aO+"_"+aQ);
aP.style.color="";var e=document.getElementById(aO+"_"+aQ+"_tab");e.className="cuesSecondaryTab cuesSecondaryTabCaptionActive";e.active="true";var e=document.getElementById(aO+"_"+aQ+"_outline");e.color=au.cuesSecondaryTabActiveStroke}function U(aR,aO){var aQ=document.getElementById(aR+"_"+aO+"_tab");aQ.className="cuesSecondaryTab cuesSecondaryTabCaptionActive";aQ.active="true";var e=document.getElementById("cuesid_"+aR+"_"+aO);e.style.color="";var aP=aQ.getElementsByTagName("rect");
aP[0].style.cssText=aP[0].style.cssText.replace("#inactivesecondarytab_grad","#activesecondarytab_grad");aP[0].style.cssText=aP[0].style.cssText.replace("#hoversecondarytab_grad","#activesecondarytab_grad");aP[0].setAttributeNS(null,"stroke",au.cuesSecondaryTabActiveStroke)}function Y(aO,aQ){var e=document.getElementById(aO+"_"+aQ+"_fill");e.color=au.cuesSecondaryTabInactiveStartGradient;e.color2=au.cuesSecondaryTabInactiveStopGradient;e.colors.value=e.inactivecolors;
var aP=document.getElementById("cuesid_"+aO+"_"+aQ);aP.style.color="";var e=document.getElementById(aO+"_"+aQ+"_tab");e.className="cuesSecondaryTab cuesSecondaryTabCaptionInactive";e.active="false";var e=document.getElementById(aO+"_"+aQ+"_outline");e.color=au.cuesSecondaryTabInactiveStroke}function j(aO,aP){var e=document.getElementById(aO+"_"+aP+"_tab");e.className="cuesSecondaryTab cuesSecondaryTabCaptionInactive";e.active="false";var aQ=e.getElementsByTagName("rect");
aQ[0].style.cssText=aQ[0].style.cssText.replace("#activesecondarytab_grad","#inactivesecondarytab_grad");aQ[0].setAttributeNS(null,"stroke",au.cuesSecondaryTabInactiveStroke)}function an(aP,aO,aV,aS){var aQ=document.getElementById(aP+"_"+aO+"_tab");if(aQ==null){return}var aR=aQ.offsetHeight;if(aR==0&&aS==null){setTimeout("cuesDrawnShape.makeSecondaryTab('"+aP+"',"+aO+","+aV+",true)",10);return}var e=aQ.offsetWidth;if(aR==0){aR=20}if(e==0){e=100}aQ.style.height=aR+1;
aQ.style.width=e;var aX=aQ.offsetWidth;if(aX==0){aX="100%"}if(aX>aQ.scrollWidth&&aX>1000){aX=aQ.scrollWidth}aQ.style.width=aX;aQ.active=aV?"true":"false";var aT=document.createElement("div");aT.style.position="absolute";aT.style.top="0px";aT.style.left="0px";aT.style.zIndex="-1";var aW=aV?"Active":"Inactive";var aU="";aU+='<cues_vml:roundrect id="'+aP+"_"+aO+'_shape" style="height:'+(2*aR)+"px;width:"+aX+"px;position:absolute;padding:0;top:0px;left:0px;margin:0;padding:0px;clip:rect(0,auto,"+(aR+2)+',auto);" arcsize="0.05">';
aU+='<cues_vml:stroke id="'+aP+"_"+aO+'_outline" dashstyle="solid" color="'+au["cuesSecondaryTab"+aW+"Stroke"]+'"/>';aU+='<cues_vml:fill id="'+aP+"_"+aO+'_fill" type="gradient"';aU+=' angle="180"';aU+=' activecolors="50% '+au.cuesSecondaryTabActiveStopGradient+'"';aU+=' inactivecolors="25% '+au.cuesSecondaryTabInactiveStopGradient1+", 26% "+au.cuesSecondaryTabInactiveStartGradient2+'"';aU+=' hovercolors="25% '+au.cuesSecondaryTabHoverStopGradient1+", 26% "+au.cuesSecondaryTabHoverStartGradient2+'"';
if(aV){aU+=' colors="50% '+au.cuesSecondaryTabActiveStopGradient+'"'}else{aU+=' colors="25% '+au.cuesSecondaryTabInactiveStopGradient1+", 26% "+au.cuesSecondaryTabInactiveStartGradient2+'"'}aU+=' color="'+au["cuesSecondaryTab"+aW+"StartGradient"]+'"';aU+=' color2="'+au["cuesSecondaryTab"+aW+"StopGradient"]+'"/>';aU+="</cues_vml:roundrect>";aT.innerHTML=aU;aQ.appendChild(aT)}function l(aP,aO,aU){var aQ=document.getElementById(aP+"_"+aO+"_tab");if(aQ==null){return
}var aS=aQ.offsetHeight;var aW=aQ.offsetWidth;aQ.style.width=aW;aQ.active=aU?"true":"false";var aX=document.createElementNS(V,"svg");aX.setAttributeNS(null,"style","position:absolute;top:0px;left:0px;z-index:-1;");aX.setAttributeNS(null,"height",aS+"px");aQ.appendChild(aX);if(aI==null){var aY="";aY+='<svg xmlns="http://www.w3.org/2000/svg">';aY+="<defs>";aY+='<linearGradient id="activesecondarytab_grad" x1="0" y1="0" x2="0" y2="100%">';aY+='<stop offset="0%" style="stop-color:'+au.cuesSecondaryTabActiveStartGradient+';stop-opacity:1;"/>';
aY+='<stop offset="50%" style="stop-color:'+au.cuesSecondaryTabActiveStopGradient+';stop-opacity:1;"/>';aY+="</linearGradient>";aY+="</defs>";aY+='<rect rx="4" ry="4" x="0" y="0" width="100%" height="200%" stroke="'+au.cuesSecondaryTabActiveStroke+'" style="fill:url(#activesecondarytab_grad);stroke-width:1px;stroke-opacity:1;"/>';aY+="</svg>";var aR=new DOMParser();aI=aR.parseFromString(aY,"text/xml")}if(u==null){var aY="";aY+='<svg xmlns="http://www.w3.org/2000/svg">';
aY+="<defs>";aY+='<linearGradient id="hoversecondarytab_grad" x1="0" y1="0" x2="0" y2="100%">';aY+='<stop offset="0%" style="stop-color:'+au.cuesSecondaryTabHoverStartGradient+';stop-opacity:1;"/>';aY+='<stop offset="25%" style="stop-color:'+au.cuesSecondaryTabHoverStopGradient1+';stop-opacity:1;"/>';aY+='<stop offset="26%" style="stop-color:'+au.cuesSecondaryTabHoverStartGradient2+';stop-opacity:1;"/>';aY+='<stop offset="50%" style="stop-color:'+au.cuesSecondaryTabHoverStopGradient+';stop-opacity:1;"/>';
aY+="</linearGradient>";aY+='<linearGradient id="inactivesecondarytab_grad" x1="0" y1="0" x2="0" y2="100%">';aY+='<stop offset="0%" style="stop-color:'+au.cuesSecondaryTabInactiveStartGradient+';stop-opacity:1;"/>';aY+='<stop offset="25%" style="stop-color:'+au.cuesSecondaryTabInactiveStopGradient1+';stop-opacity:1;"/>';aY+='<stop offset="26%" style="stop-color:'+au.cuesSecondaryTabInactiveStartGradient2+';stop-opacity:1;"/>';aY+='<stop offset="50%" style="stop-color:'+au.cuesSecondaryTabInactiveStopGradient+';stop-opacity:1;"/>';
aY+="</linearGradient>";aY+="</defs>";aY+='<rect rx="4" ry="4" x="0" y="0" width="100%" height="200%" stroke="'+au.cuesSecondaryTabInactiveStroke+'" style="fill:url(#inactivesecondarytab_grad);stroke-width:1.5px;stroke-opacity:1;"/>';aY+="</svg>";var aR=new DOMParser();u=aR.parseFromString(aY,"text/xml")}var aV;if(aU){aV=aI.documentElement}else{aV=u.documentElement}var e=aV.childNodes.length;for(var aT=0;aT<e;++aT){aX.appendChild(document.importNode(aV.childNodes[aT],true))
}}function ah(aO,e){var aP=document.getElementById(aO+"_"+e+"_tab");if(aP==null){return}if(aP.active=="true"){return}var aQ=document.getElementById("cuesid_"+aO+"_"+e);aQ.style.color=au.cuesSecondaryTabCaptionHover;var aP=document.getElementById(aO+"_"+e+"_fill");if(aP==null){return}aP.color=au.cuesSecondaryTabHoverStartGradient;aP.color2=au.cuesSecondaryTabHoverStopGradient;aP.colors.value=aP.hovercolors;var aP=document.getElementById(aO+"_"+e+"_outline");
aP.color=au.cuesSecondaryTabHoverStroke}function E(aO,e){var aP=document.getElementById(aO+"_"+e+"_tab");if(aP==null){return}if(aP.active=="true"){return}var aQ=document.getElementById("cuesid_"+aO+"_"+e);aQ.style.color=au.cuesSecondaryTabCaptionInactive;var aP=document.getElementById(aO+"_"+e+"_fill");if(aP==null){return}aP.color=au.cuesSecondaryTabInactiveStartGradient;aP.color2=au.cuesSecondaryTabInactiveStopGradient;aP.colors.value=aP.inactivecolors;
var aP=document.getElementById(aO+"_"+e+"_outline");aP.color=au.cuesSecondaryTabInactiveStroke}function ab(aR,aP){var e=document.getElementById(aR+"_"+aP+"_tab");if(e==null){return}if(e.active=="true"){return}var aO=document.getElementById("cuesid_"+aR+"_"+aP);aO.style.color=au.cuesSecondaryTabCaptionHover;var aQ=e.getElementsByTagName("rect")[0];aQ.style.cssText=aQ.style.cssText.replace("url(#inactivesecondarytab_grad)","url(#hoversecondarytab_grad)");
aQ.setAttributeNS(null,"stroke",au.cuesSecondaryTabHoverStroke)}function a(aR,aP){var e=document.getElementById(aR+"_"+aP+"_tab");if(e==null){return}if(e.active=="true"){return}var aO=document.getElementById("cuesid_"+aR+"_"+aP);aO.style.color=au.cuesSecondaryTabCaptionInactive;var aQ=e.getElementsByTagName("rect")[0];aQ.style.cssText=aQ.style.cssText.replace("url(#hoversecondarytab_grad)","url(#inactivesecondarytab_grad)");aQ.setAttributeNS(null,"stroke",au.cuesSecondaryTabInactiveStroke)
}function aA(e,aO){var aP=false;try{var aR=document.getElementById(e);if(aR!=null){aR.className="cuesDrawer cuesDrawerCaptionActive";aR.active="true";var aR=document.getElementById(e+"_fill");if(aR!=null){aP=true;aR.color=au.cuesDrawerActiveStartGradient;aR.color2=au.cuesDrawerActiveStopGradient;aR.colors.value=""}}}catch(aQ){}return aP}function W(aP){try{var aO=document.getElementById(aP);aO.className="cuesDrawer cuesDrawerCaptionActive";aO.setAttribute("active","true");
var aQ=aO.getElementsByTagName("rect")[0];aQ.style.cssText=aQ.style.cssText.replace("#inactivedrawer_grad","#activedrawer_grad");aQ.style.cssText=aQ.style.cssText.replace("#hoverdrawer_grad","#activedrawer_grad");return true}catch(e){}return false}function aw(aP,aQ){try{var aO=document.getElementById(aP);if(aO!=null){aO.className="cuesDrawer cuesDrawerCaptionInactive";aO.active="false";var aO=document.getElementById(aP+"_fill");if(aO!=null){aO.color=au.cuesDrawerInactiveStartGradient;
aO.color2=au.cuesDrawerInactiveStopGradient;aO.colors.value=aO.inactivecolors}else{if(aQ==null){setTimeout("cuesDrawnShape.makeDrawerInactive('"+aP+"',true)",10)}}}}catch(e){}}function C(aO){var e=document.getElementById(aO);e.className="cuesDrawer cuesDrawerCaptionInactive";e.setAttribute("active","false");var aP=e.getElementsByTagName("rect")[0];aP.style.cssText=aP.style.cssText.replace("#activedrawer_grad","#inactivedrawer_grad")}function Q(e,aQ){var aP=document.getElementById(e);
if(aP==null){return}if(aQ!=null){aP.style.width=(aQ-1)+"px"}else{aP.style.width=(aP.parentNode.parentNode.clientWidth-1)+"px"}var aO=aP.getElementsByTagName("rect");if(aO.length==0){return}aO[0].style.width=aP.offsetWidth;aO[0].style.height=aP.offsetHeight;if(aP.active=="true"){cuesDrawnShape.makeDrawerActive(e)}}function d(e,aQ){var aP=document.getElementById(e);if(aP==null){return}if(aQ!=null){aP.style.width=aQ+"px"}else{aP.style.width=aP.parentNode.offsetWidth+"px"
}var aO=document.getElementById(e+"_svg");if(aO==null){return}aO.setAttributeNS(null,"height",aP.offsetHeight+"px");aO.setAttributeNS(null,"width",aP.offsetWidth+"px")}function x(aV,e){var aQ=document.getElementById(aV);if(aQ==null){return}var aS=aQ.offsetHeight;var aU=aQ.offsetWidth;if(aU==0){var aR=aQ.parentNode;while(aR!=null&&aU==0){try{if(aR.currentStyle.width!="auto"){aU=parseInt(aR.currentStyle.width+" ")}}catch(aT){}aR=aR.parentNode}if(aU>1){aU--
}}aQ.active="false";if(aS==0){aS=30}if(aU==0){aU=200}var aP=document.createElement("div");aP.style.position="absolute";aP.style.top="0px";aP.style.left="0px";aP.style.width="600px";aP.style.height="300px";aP.style.zIndex="-1";aP.style.overflow="hidden";var aO="";aO+='<cues_vml:rect style="height:'+aS+"px;width:"+aU+'px;position:absolute;padding:0;top:0px;left:0px;margin:0;padding:0px;">';aO+='<cues_vml:stroke id="'+aV+'_stroke" dashstyle="solid" color="'+au.cuesDrawerInactiveStroke+'"/>';
aO+='<cues_vml:fill id="'+aV+'_fill" type="gradient" angle="180"';aO+=' colors="'+am+" "+au.cuesDrawerInactiveStopGradient1+", "+ay+" "+au.cuesDrawerInactiveStartGradient2+", "+af+" "+au.cuesDrawerInactiveStopGradient2+", "+v+" "+au.cuesDrawerInactiveStartGradient3+'"';aO+=' inactivecolors="'+am+" "+au.cuesDrawerInactiveStopGradient1+", "+ay+" "+au.cuesDrawerInactiveStartGradient2+", "+af+" "+au.cuesDrawerInactiveStopGradient2+", "+v+" "+au.cuesDrawerInactiveStartGradient3+'"';
aO+=' hovercolors="'+Z+" "+au.cuesDrawerHoverStopGradient1+", "+ae+" "+au.cuesDrawerHoverStartGradient2+'"';aO+=' color="'+au.cuesDrawerInactiveStartGradient+'"';aO+=' color2="'+au.cuesDrawerInactiveStopGradient+'"/>';aO+="</cues_vml:rect>";aP.innerHTML=aO;aQ.appendChild(aP)}function o(aV){var aP=document.getElementById(aV);if(aP==null){return}var aR=aP.offsetHeight;var aQ=aP.offsetWidth;aP.style.width=aQ;aP.setAttribute("active","false");var aU=document.createElementNS(V,"svg");
aU.setAttributeNS(null,"style","position:absolute;top:0px;left:0px;z-index:-1;");aU.setAttributeNS(null,"height",aP.offsetHeight+"px");aU.setAttributeNS(null,"id",aV+"_svg");aU.setAttributeNS(null,"shape-rendering","geometric-precision");aP.appendChild(aU);if(aH==null){var aW="";aW+='<svg xmlns="http://www.w3.org/2000/svg">';aW+="<defs>";aW+='<linearGradient id="activedrawer_grad" x1="0" y1="0" x2="0" y2="100%">';aW+='<stop offset="0%" style="stop-color:'+au.cuesDrawerActiveStartGradient+';stop-opacity:1;"/>';
aW+='<stop offset="100%" style="stop-color:'+au.cuesDrawerActiveStopGradient+';stop-opacity:1;"/>';aW+="</linearGradient>";aW+='<linearGradient id="hoverdrawer_grad" x1="0" y1="0" x2="0" y2="100%">';aW+='<stop offset="0%" style="stop-color:'+au.cuesDrawerHoverStartGradient+';stop-opacity:1;"/>';aW+='<stop offset="'+Z+'" style="stop-color:'+au.cuesDrawerHoverStopGradient1+';stop-opacity:1;"/>';aW+='<stop offset="'+ae+'" style="stop-color:'+au.cuesDrawerHoverStartGradient2+';stop-opacity:1;"/>';
aW+='<stop offset="100%" style="stop-color:'+au.cuesDrawerHoverStopGradient+';stop-opacity:1;"/>';aW+="</linearGradient>";aW+='<linearGradient id="inactivedrawer_grad" x1="0" y1="0" x2="0" y2="100%">';aW+='<stop offset="0%" style="stop-color:'+au.cuesDrawerInactiveStartGradient+';stop-opacity:1;"/>';aW+='<stop offset="'+am+'" style="stop-color:'+au.cuesDrawerInactiveStopGradient1+';stop-opacity:1;"/>';aW+='<stop offset="'+ay+'" style="stop-color:'+au.cuesDrawerInactiveStartGradient2+';stop-opacity:1;"/>';
aW+='<stop offset="'+af+'" style="stop-color:'+au.cuesDrawerInactiveStopGradient2+';stop-opacity:1;"/>';aW+='<stop offset="'+v+'" style="stop-color:'+au.cuesDrawerInactiveStartGradient3+';stop-opacity:1;"/>';aW+='<stop offset="100%" style="stop-color:'+au.cuesDrawerInactiveStopGradient+';stop-opacity:1;"/>';aW+="</linearGradient>";aW+="</defs>";aW+='<rect x="0" y="0" width="100%" height="100%" style="fill:url(#inactivedrawer_grad);stroke:'+au.cuesDrawerInactiveStroke+';stroke-width:2px;stroke-opacity:.5;"/>';
aW+="</svg>";var aO=new DOMParser();aH=aO.parseFromString(aW,"text/xml")}var e=aH.documentElement;var aS=e.childNodes.length;for(var aT=0;aT<aS;++aT){aU.appendChild(document.importNode(e.childNodes[aT],true))}}function S(aP){try{var aO=document.getElementById(aP);if(aO==null){return}if(aO.active=="true"){return}var aO=document.getElementById(aP+"_fill");if(aO==null){return}aO.color=au.cuesDrawerHoverStartGradient;aO.color2=au.cuesDrawerHoverStopGradient;
aO.colors.value=aO.hovercolors}catch(e){}}function f(aO){var e=document.getElementById(aO);if(e==null){return}if(e.active=="true"){return}var e=document.getElementById(aO+"_fill");if(e==null){return}e.color=au.cuesDrawerInactiveStartGradient;e.color2=au.cuesDrawerInactiveStopGradient;e.colors.value=e.inactivecolors}function aj(aQ){try{var aP=document.getElementById(aQ);if(aP==null){return}if(aP.getAttribute("active")=="true"){return}var e=aP.getElementsByTagName("rect")[0];
e.style.cssText=e.style.cssText.replace("url(#inactivedrawer_grad)","url(#hoverdrawer_grad)")}catch(aO){}}function aL(aQ){try{var aP=document.getElementById(aQ);if(aP==null){return}if(aP.getAttribute("active")=="true"){return}var e=aP.getElementsByTagName("rect")[0];e.style.cssText=e.style.cssText.replace("url(#hoverdrawer_grad)","url(#inactivedrawer_grad)")}catch(aO){}}function ax(aQ,aS){var aR=document.getElementById(aQ);if(aR==null){return}var aO=aR.offsetHeight;
if(aO==0&&aS==null){setTimeout("cuesDrawnShape.makeDashboard('"+aQ+"',true)",250);return}aO=Math.max(aO,23);var e=document.getElementById(aQ+".graphic");if(e==null){e=document.createElement("div");e.id=aQ+".graphic";e.style.position="absolute";e.style.top="0px";e.style.left="0px";e.style.width="100%";e.style.height=Math.max(1,aO-1);e.style.zIndex="-2";e.style.overflow="hidden";e.style.paddingRight=1}var aP="";aP+='<cues_vml:roundrect style="height:'+Math.ceil(aO*2)+"px;width:100%;position:absolute;padding:0;top:0px;left:0px;margin:0;padding:0px;clip:rect(0,auto,"+(aO+1)+',auto);" arcsize="0.05" strokecolor="'+au.cuesDashboardStroke+'">';
aP+='<cues_vml:fill type="gradient" angle="180"';aP+=' colors="0 '+au.cuesDashboardStartGradient+", "+ai+" "+au.cuesDashboardStopGradient1+", "+aB+" "+au.cuesDashboardStartGradient2+'"';aP+=' color2="'+au.cuesDashboardStopGradient+'"/>';aP+="</cues_vml:roundrect>";aP+='<cues_vml:rect style="height:'+(aO/2)+"px;width:100%;position:absolute;padding:0;top:"+Math.ceil(aO/2)+'px;left:0px;margin:0;padding:0px;" stroked="false">';aP+='<cues_vml:fill type="gradient" angle="180"';
aP+=' colors="0 '+au.cuesDashboardStartGradient2+'"';aP+=' color2="'+au.cuesDashboardStopGradient+'"/>';aP+="</cues_vml:rect>";e.innerHTML=aP;aR.appendChild(e)}function ac(aP,aS){if(document.getElementById(aP+".graphic")!=null){return}var aQ=document.getElementById(aP);if(aQ==null){return}var aW=document.createElementNS(V,"svg");aW.setAttributeNS(null,"id",aP+".graphic");aW.setAttributeNS(null,"style","position:absolute;top:0px;left:0px;z-index:-1;");
aW.setAttributeNS(null,"height","22px");aW.setAttributeNS(null,"width","100%");aQ.appendChild(aW);var aR=aQ.getElementsByTagName("table")[0];var e=Math.max(22,parseInt(aR.offsetHeight));aW.setAttributeNS(null,"height",e+"px");if(c==null){var aX="";aX+='<svg xmlns="http://www.w3.org/2000/svg">';aX+="<defs>";aX+='<linearGradient id="dashboard_grad" x1="0" y1="0" x2="0" y2="100%">';aX+='<stop offset="0%" style="stop-color:'+au.cuesDashboardStartGradient+';stop-opacity:1;"/>';
aX+='<stop offset="'+ai+'" style="stop-color:'+au.cuesDashboardStopGradient1+';stop-opacity:1;"/>';aX+='<stop offset="'+aB+'" style="stop-color:'+au.cuesDashboardStartGradient2+';stop-opacity:1;"/>';aX+='<stop offset="100%" style="stop-color:'+au.cuesDashboardStopGradient+';stop-opacity:1;"/>';aX+="</linearGradient>";aX+='<clipPath id="dashboard_clip">';aX+='<rect x="0" y="0" width="99.999%" height="100%"/>';aX+="</clipPath>";aX+="</defs>";aX+='<rect rx="4" ry="4" x="0" y="0" width="100%" height="220%" style="fill:url(#dashboard_grad);stroke:'+au.cuesDashboardStroke+';stroke-width:1.7px;stroke-opacity:1;"/>';
aX+="</svg>";var aO=new DOMParser();c=aO.parseFromString(aX,"text/xml")}var aV=c.documentElement;var aU=aV.childNodes.length;for(var aT=0;aT<aU;++aT){aW.appendChild(document.importNode(aV.childNodes[aT],true))}}function aD(aQ,aS){var aR=document.getElementById(aQ);if(aR==null){return}var aO=aR.offsetHeight;if(aO==0&&aS==null){setTimeout("cuesDrawnShape.makePanel('"+aQ+"',true)",250);return}var e=document.createElement("div");e.style.position="absolute";
e.style.top="0px";e.style.left="-20px";e.style.width="200%";e.style.height=Math.max(0,aO-1);e.style.zIndex="-2";e.style.overflow="hidden";var aP="";aP+='<cues_vml:roundrect style="height:'+Math.ceil(aO*2)+"px;width:100%;position:absolute;padding:0;top:0px;left:0px;margin:0;padding:0px;clip:rect(0,auto,"+(aO+1)+',auto);" arcsize="0.05" strokecolor="'+au.cuesDashboardStroke+'">';aP+='<cues_vml:fill type="gradient" angle="180"';aP+=' colors="0 '+au.cuesDashboardStartGradient+", "+ai+" "+au.cuesDashboardStopGradient1+", "+aB+" "+au.cuesDashboardStartGradient2+'"';
aP+=' color2="'+au.cuesDashboardStopGradient+'"/>';aP+="</cues_vml:roundrect>";e.innerHTML=aP;aR.appendChild(e)}function z(aP,e){var aQ=document.getElementById(aP);if(aQ==null){return}var aV=document.createElementNS(V,"svg");aV.setAttributeNS(null,"style","position:absolute;top:0px;left:0px;z-index:-1");aV.setAttributeNS(null,"height","31px");aV.setAttributeNS(null,"width","100%");aQ.appendChild(aV);var aS=parseInt(aQ.offsetHeight);aV.setAttributeNS(null,"height",aS+"px");
if(c==null){var aW="";aW+='<svg xmlns="http://www.w3.org/2000/svg">';aW+="<defs>";aW+='<linearGradient id="dashboard_grad" x1="0" y1="0" x2="0" y2="100%">';aW+='<stop offset="0%" style="stop-color:'+au.cuesDashboardStartGradient+';stop-opacity:1;"/>';aW+='<stop offset="'+ai+'" style="stop-color:'+au.cuesDashboardStopGradient1+';stop-opacity:1;"/>';aW+='<stop offset="'+aB+'" style="stop-color:'+au.cuesDashboardStartGradient2+';stop-opacity:1;"/>';aW+='<stop offset="100%" style="stop-color:'+au.cuesDashboardStopGradient+';stop-opacity:1;"/>';
aW+="</linearGradient>";aW+="</defs>";aW+='<rect rx="4" ry="4" x="0" y="0" width="100%" height="200%" style="fill:url(#dashboard_grad);stroke:'+au.cuesDashboardStroke+';stroke-width:1px;stroke-opacity:1;"/>';aW+="</svg>";var aO=new DOMParser();c=aO.parseFromString(aW,"text/xml")}var aU=c.documentElement;var aR=aU.childNodes.length;for(var aT=0;aT<aR;++aT){aV.appendChild(document.importNode(aU.childNodes[aT],true))}}function R(aP,aR,aU,aT){var aQ=document.getElementById(aP);
if(aQ==null){return}var e=aQ.offsetHeight;if(e==0&&aT==null){setTimeout("cuesDrawnShape.makeContainer('"+aP+"','"+aR+"','"+aU+"',true)",100);return}var aS=aP+".layer";var aO=document.getElementById(aS);if(aO==null){aO=document.createElement("div");aO.id=aS;aO.style.zIndex=-2;aO.style.position="absolute";aO.style.width=aQ.offsetWidth;aO.style.height=e;aO.style.top="0";aO.style.left="0";var aV="";aV+='<cues_vml:roundrect style="height:100%;width:100%;padding:0;top:0px;left:0px;margin:0;padding:0px;" arcsize="0.05">';
aV+='<cues_vml:stroke opacity="'+aU+'" color="'+aR+'"/>';aV+='<cues_vml:fill color="'+aR+'" opacity="'+aU+'"/>';aV+="</cues_vml:roundrect>";aO.innerHTML=aV;aQ.appendChild(aO)}else{aO.style.width=aQ.offsetWidth;aO.style.height=e}}function k(aQ,aU,aO,e){var aR=document.getElementById(aQ);if(aR==null){return}if(e==null){setTimeout("cuesDrawnShape.makeContainer('"+aQ+"','"+aU+"','"+aO+"',true)",100);return}if(aO.indexOf("%")!=-1){aO=aO.replace("%","");
if(aO==100){aO=1}else{aO="."+aO}}var aT=aQ+".layer";var aS=document.getElementById(aT);if(aS==null){aS=document.createElementNS(V,"svg");aS.setAttributeNS(null,"id",aT);aS.setAttributeNS(null,"style","position:absolute;top:0px;left:0px;z-index:-1");aS.setAttributeNS(null,"height",aR.offsetHeight);aS.setAttributeNS(null,"width",aR.offsetWidth);aR.appendChild(aS);var aP=document.createElementNS(V,"rect");aP.setAttributeNS(null,"rx",4);aP.setAttributeNS(null,"ry",4);
aP.setAttributeNS(null,"x",0);aP.setAttributeNS(null,"y",0);aP.setAttributeNS(null,"width","100%");aP.setAttributeNS(null,"height","100%");aP.setAttributeNS(null,"style","fill:"+aU+";stroke:"+aU+";opacity:"+aO+";stroke-width:1px;stroke-opacity:"+aO+";");aS.appendChild(aP)}else{aS.setAttributeNS(null,"height",aR.offsetHeight);aS.setAttributeNS(null,"width",aR.offsetWidth)}}function p(e){var aO=document.getElementById(e);if(aO==null){return}var aP="";
aP+='<cues_vml:rect id="'+e+'.bar1" style="height:17px;width:0px;padding:0;top:0px;left:0px;margin:0;position:absolute;" stroked="f">';aP+='<cues_vml:stroke color="'+au.cuesProgressBarTop+'"/>';aP+='<cues_vml:fill color="'+au.cuesProgressBarTop+'"/>';aP+="</cues_vml:rect>";aP+='<cues_vml:rect id="'+e+'.bar2" style="height:9px;width:0px;padding:0;top:8px;left:0px;margin:0;position:absolute;" stroked="f">';aP+='<cues_vml:stroke color="'+au.cuesProgressBarBottom+'"/>';
aP+='<cues_vml:fill color="'+au.cuesProgressBarBottom+'"/>';aP+="</cues_vml:rect>";aO.innerHTML=aP}function r(aO){var aP=document.getElementById(aO);if(aP==null){return}var aQ=document.createElementNS(V,"svg");aQ.setAttributeNS(null,"height","17px");aQ.setAttributeNS(null,"width","270px");aQ.setAttributeNS(null,"style","position:absolute;top:0;left:0;");aP.appendChild(aQ);var e=document.createElementNS(V,"rect");e.setAttributeNS(null,"id",aO+".bar1");
e.setAttributeNS(null,"x",0);e.setAttributeNS(null,"y",0);e.setAttributeNS(null,"width","0px");e.setAttributeNS(null,"height","17px");e.setAttributeNS(null,"style","fill:"+au.cuesProgressBarTop+";");aQ.appendChild(e);var e=document.createElementNS(V,"rect");e.setAttributeNS(null,"id",aO+".bar2");e.setAttributeNS(null,"x",0);e.setAttributeNS(null,"y",8);e.setAttributeNS(null,"width","0px");e.setAttributeNS(null,"height","9px");e.setAttributeNS(null,"style","fill:"+au.cuesProgressBarBottom+";");
aQ.appendChild(e)}function G(aR,aP){aP=Math.min(100,aP);aP=Math.max(0,aP);var e=270*(aP/100);var aQ=document.getElementById(aR+".bar1");if(aQ!=null){aQ.stroked="t";aQ.style.width=e}var aQ=document.getElementById(aR+".bar2");if(aQ!=null){aQ.stroked="t";aQ.style.width=e}var aO=document.getElementById(aR+".percent");if(aO!=null){aO.innerHTML=aP+"%"}}function ao(aR,aP){aP=Math.min(100,aP);aP=Math.max(0,aP);var e=271*(aP/100);var aQ=document.getElementById(aR+".bar1");
if(aQ!=null){aQ.setAttributeNS(null,"width",e+"px")}var aQ=document.getElementById(aR+".bar2");if(aQ!=null){aQ.setAttributeNS(null,"width",e+"px")}var aO=document.getElementById(aR+".percent");if(aO!=null){aO.innerHTML=aP+"%"}}function aM(aQ,aV,e){var aR=document.getElementById(aQ);if(aR==null){return}var aS=aR.offsetHeight;if(aS==0&&e==null){setTimeout("cuesDrawnShape.makeToolbar('"+aQ+"','"+aV+"',true)",250);return}var aO=(aV=="main"?"67":"40");
try{aS=Math.max(aS,aR.firstChild.offsetHeight)}catch(aU){}var aP=document.createElement("div");aP.style.zIndex=-2;aP.style.position="absolute";aP.style.width="100%";var aT="";aT+='<cues_vml:roundrect style="filter:alpha(opacity='+aO+");height:"+(aS-1)+'px;width:100%;padding:0;top:0px;left:0px;margin:0;padding:0px;" arcsize="0.08" ';if(aV=="main"){aT+='strokecolor="'+au.cuesToolbarFill+'">'}else{aT+='strokecolor="'+au.cuesToolbarStroke+'">'}aT+='<cues_vml:fill color="'+au.cuesToolbarFill+'" opacity="'+aO+'"/>';
aT+="</cues_vml:roundrect>";aP.innerHTML=aT;aR.insertBefore(aP,aR.firstChild);aR.style.height=aS}function B(aQ,aV){var aR=document.getElementById(aQ);if(aR==null){return}var aX=document.createElementNS(V,"svg");aX.setAttributeNS(null,"style","position:absolute;top:0px;left:0px;z-index:-1");aX.setAttributeNS(null,"height","31px");aX.setAttributeNS(null,"width","100%");aR.appendChild(aX);var aO=parseInt(aR.offsetHeight);try{var aS=aR.getElementsByTagName("table")[0];
aO=Math.max(aO,parseInt(aS.offsetHeight))}catch(aU){}aX.setAttributeNS(null,"height",aO+"px");if(aq==null&&aV=="main"){var aY="";aY+='<svg xmlns="http://www.w3.org/2000/svg">';aY+='<rect rx="3" ry="3" x="0" y="0" width="100%" height="100%" style="fill:'+au.cuesToolbarFill+";stroke:"+au.cuesToolbarStroke+';stroke-width:0px;stroke-opacity:0;opacity:.67;"/>';aY+="</svg>";var aP=new DOMParser();aq=aP.parseFromString(aY,"text/xml")}if(F==null&&aV=="content"){var aY="";
aY+='<svg xmlns="http://www.w3.org/2000/svg">';aY+='<rect rx="3.3" ry="3.3" x="0" y="0" width="100%" height="100%" style="fill:'+au.cuesToolbarFill+";stroke:"+au.cuesToolbarStroke+';stroke-width:.9px;stroke-opacity:1;opacity:.4;"/>';aY+="</svg>";var aP=new DOMParser();F=aP.parseFromString(aY,"text/xml")}var aW=(aV=="main"?aq.documentElement:F.documentElement);var aT=aW.childNodes.length;for(var e=0;e<aT;++e){aX.appendChild(document.importNode(aW.childNodes[e],true))
}aR.style.height=aO}function w(){try{if(au!=null){return}au=new Array();au.cuesTabStroke="#8499a2";au.cuesTabActiveStartGradient="#f7f9fb";au.cuesTabActiveStopGradient="#ffffff";au.cuesTabActiveStroke="#8499a2";au.cuesTabInactiveStartGradient="#feffff";au.cuesTabInactiveStopGradient1="#dae4ea";au.cuesTabInactiveStartGradient2="#cbd8e1";au.cuesTabInactiveStopGradient2="#b4c7d4";au.cuesTabInactiveStopGradient="#c1d0db";au.cuesTabInactiveStroke="#8499a2";
au.cuesTabCaptionInactive="#000000";au.cuesTabHoverStartGradient="#e8f6fb";au.cuesTabHoverStopGradient1="#8ad8ef";au.cuesTabHoverStartGradient2="#64ccec";au.cuesTabHoverStopGradient="#c6f5fe";au.cuesTabHoverStroke="#1fa0d5";au.cuesTabCaptionHover="#000000";au.cuesDrawerActiveStartGradient="#add050";au.cuesDrawerActiveStopGradient="#8db71f";au.cuesDrawerActiveStroke="#8499a2";au.cuesDrawerCaptionActive="#ffffff";au.cuesDrawerInactiveStartGradient="#feffff";
au.cuesDrawerInactiveStopGradient1="#dae4ea";au.cuesDrawerInactiveStartGradient2="#dae4ea";au.cuesDrawerInactiveStopGradient2="#cbd8e1";au.cuesDrawerInactiveStartGradient3="#b4c7d4";au.cuesDrawerInactiveStopGradient="#c1d0db";au.cuesDrawerInactiveStroke="#53636a";au.cuesDrawerCaptionInactive="#000000";au.cuesDrawerHoverStartGradient="#e8f6fb";au.cuesDrawerHoverStopGradient1="#8ad8ef";au.cuesDrawerHoverStartGradient2="#64ccec";au.cuesDrawerHoverStopGradient="#c6f5fe";
au.cuesDrawerCaptionHover="#333333";au.cuesPrimaryTabsetStartGradient="#ffffff";au.cuesPrimaryTabsetStopGradient="#ffffff";au.cuesPrimaryTabsetStroke="#ffffff";au.cuesPrimaryTabStroke="#1fa0d5";au.cuesPrimaryTabActiveStartGradient="#add050";au.cuesPrimaryTabActiveStopGradient="#8db71f";au.cuesPrimaryTabActiveStroke="#8499a2";au.cuesPrimaryTabCaptionInactive="#ffffff";au.cuesPrimaryTabHoverStartGradient="#22a2d6";au.cuesPrimaryTabHoverStopGradient="#95edfd";
au.cuesPrimaryTabHoverStroke="#1fa0d5";au.cuesPrimaryTabCaptionHover="#000000";au.cuesSecondaryTabActiveStartGradient="#add050";au.cuesSecondaryTabActiveStopGradient="#8db71f";au.cuesSecondaryTabActiveStroke="#8499a2";au.cuesSecondaryTabCaptionInactive="#ffffff";au.cuesSecondaryTabInactiveStartGradient="#84939a";au.cuesSecondaryTabInactiveStopGradient1="#687b85";au.cuesSecondaryTabInactiveStartGradient2="#314c5a";au.cuesSecondaryTabInactiveStopGradient="#355261";
au.cuesSecondaryTabInactiveStroke="#2f4955";au.cuesSecondaryTabHoverStartGradient="#e8f6fb";au.cuesSecondaryTabHoverStopGradient1="#8ad8ef";au.cuesSecondaryTabHoverStartGradient2="#64ccec";au.cuesSecondaryTabHoverStopGradient="#c6f5fe";au.cuesSecondaryTabHoverStroke="#1fa0d5";au.cuesSecondaryTabCaptionHover="#000000";au.cuesDashboardStartGradient="#84939a";au.cuesDashboardStopGradient1="#687b85";au.cuesDashboardStartGradient2="#314c5a";au.cuesDashboardStopGradient="#355261";
au.cuesDashboardStroke="#2f4955";au.cuesToolbarFill="#ffffff";au.cuesToolbarStroke="#8499a2";au.cuesProgressBarTop="#8aa54a";au.cuesProgressBarBottom="#689b01"}catch(e){}}};